appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: f44+PQf44vu/33qud/BdwCY0iBf3mo9EeqMzcOQNPDAdVUUrHvUSuSoovTQCQZf5IeShgVak2rKxx65l8mlDu6EWbTL0MysvIeSnGenX40xXzoak7Nz+D+CIu4l57FnNzCdPtLi4I4mFVgPmkSPTOc9x03Sn7swUF9WIqiEkDlYuxUTpzNRNoywaJ5h0f6wD/Rgn/V/ih89m+fIIVgQ/3ayaGN2H0uZL5La30Y5cyjCf1JyghIPs0s1bpe6qoo978pomPkNDUMhn+0NlhEkSPeBn/nfkPegDVcSNQyOiRIhnB/R3pVT6E5Pb4ahAjyxxnpafY5Y7DY5r2gvd6c/g0tQwRwIr7ULP2zL95psFp10WMPhdK9iV/xBljVxyPLMrl+siaFYpYCyVTXTQiHgWHQV79/jUAJRSND8WXzZr8M09/s5uHzTSSNMa71LnImrJxuZzHXuusmP4hMal8MF08chWGMo3b9wHedmwBsCsY88DFX6lSHOC31VmkSh3SQiZ6qkNvt8R9cVESkjAzwCz/mDhasEar3Rgrmuuj+0cotmUovRg42iev8RvHrDq9tEOjEz/j8JkeTAsQL2bsCnK9MT1PgPqLPK7dX1K749YZfWvT/jmC7MxDmqfmt+a0gzpX61NICAX4rU17IguBkCQzyqL6fzAN8+FfGVjTT8tG2A=
