travis:
  secure:
    BINSTAR_TOKEN: qLXhwBbrEkeG3MxJHWeD4G/ME9D883RfBeJMLQs3isSykCD0ZwsuRMvinjwu88X6xBCtJsZFNkucWM4LvOTlGV8h7sjh3MLveIjKa54fmjWzjo4IEYDXTQR0s3mBJYRxXTOOWw1nj6Z+KB4yvwy10iT4WYrvl4bkiHOVOeq4cAqcA1OPTMqFRYMMehQcUVvX0qE2a/2YhDO8FUxL+833aYB7EHRLumDOP9z6AOiWBKHMeqLhuI0+InelJ+hH301So49BHA7rCccVm6ugMW+pM0Ln8etuNi9o/dKSpshUd/12gVqCUK+5gqfjofQgzn/EAvhEGvmVnYNq9+bppcmzV7OTcm1F2bTUIe5JWikZ/ZGtzBw9WqVx/bDG2AxVeyFvwWhdxNozEjGnHw4lxx2Js8fN47mQOgCMZlCQKYPgR6sj2rnDM3lfQc1OVO1HH75CP3Os6n5rfg4Cpn0MbZXjKCUsWBeVag/iM8y695tNbDJgeL3EfuKJTmLz9ivywhbp29b9EFlIZuo2BUfm1BBhPGDZSnejmMP6DC/l/QCloau1rWoCghJqO4wqmlC7i019UfraeIuKp230ratZuxBYtUhZ8WWectocm42oGvniyI0kr6eKQjWC2P3k52DA7MIPxmNW+yGTx6WNsVNikugZGgY+fqdyJV2uxFD3LxulmJ4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
